version: "3.8"
services:
  app:
    build: .
    container_name: voc-container
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
